name: ChestSorter
version: '1.0'
main: com.shweit.sorter.Sorter
api-version: '1.21'
authors: [ Shweit ]

commands:
  sortcontainer:
    description: Sorts the selected container
    usage: /sortcontainer <x> <y> <z> [sortType] [sortOrder]
    aliases: [sc]

  sortplayer:
    description: Sorts the player's inventory
    usage: /sortplayer [player] [sortType] [sortOrder]
    aliases: [sp]
